# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'ReactiveListViewKitDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReactiveListViewKitDemo
  # pod 'ReactiveListViewKit'
  pod 'SDWebImage', '~> 4.0'
end

target 'ReactiveListViewKitDemoTests' do
    # Unit Test; Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for ReactiveListViewKitDemo
    # pod 'ReactiveListViewKit'
    pod 'KIF', :configurations => ['Debug']
    pod 'SDWebImage', '~> 4.0'
end

