# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactiveListViewKitDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReactiveListViewKitDemo
  pod 'SDWebImage', '~> 4.0'
  pod 'EasyMapping', '~> 0.20'
  pod ‘Reveal-SDK’

end
